### PR TITLE
Change: Parse files outside Eirene class

### PR DESCRIPTION
**Pull request by Mateasek**
Parsing moved outside of Eirene class. Related to #18.

function load_fort44_file from eirene/fort44/identify.py searches for the appropriate file parsing function for the file, calls it and returns dictionary with data. 

Functions parsing Eirene fort44 files distributed into fort44_*.py files. Parser parsing code blocks moved to parser.py

I have tested the changes only for the 2017 file version, because I don't have any other available. I would like to ask @jacklovell or @mattngc to test the 2013 file version is possible. Thanks

### CODE REVIEW

**Comment by Mateasek** [comment]
I've worked in suggestions made by @CnlPepper in #19

**Comment by jacklovell** [comment]
I've tested this, and it seems to work OK on both the 2013 and 2017 files I have access to.

**Comment by Mateasek** [comment]
Would it be possible to get this merged to the development branch, if there are no more change requests?

**Comment by jacklovell** [comment]
No objections here. @mattngc @CnlPepper?

**Comment by mattngc** [comment]
No problems from my side.

**Comment by mattngc** [comment]
I think @jacklovell has maintainer access for this repo, so he should be able to merge when ready.

**Comment by Mateasek** [comment]
thanks

**Pull request merged**
