### PR TITLE
Add support for reading 2017 fort.44 files.

### PR DESCRIPTION
**Pull request by jacklovell**
The fort.44 file format changes between SOLPS releases. This commit
adds support for the 2017 format, and also explicitly checks the format
ID of the file to ensure it is in a format Cherab understands.

### CODE REVIEW

**Comment by jacklovell** [comment]
@Mateasek could you please test this with the files you found were failing (as you mentioned in #15) to see if it fixes that problem?

**Review by mattngc — APPROVED** [review]
Nice work, looks fine to me. Obviously important to here @Mateasek's feedback on the tests.

Do you have any ideas how many legitimate SOLPS / Eirene formats there are? If there are a lot then it may be easier to redesign this and simply have a class per valid format. Overriding the base functions where necessary, etc...

**Comment by jacklovell** [comment]
I've come across at least 4 formats so far, but I don't know how different they are: the format ID appears to be tied to particular versions of Eirene which are then tied to particular versions of SOLPS.

I think it's valuable to have a single class which abstracts away the fort.44 format, and an automatic dispatch to the file reading routines once the format of the file is detected. This will make user code significantly simpler, and more reusable across different SOLPS runs. Cherab is only using a subset of the data stored in the fort.44 file, so the `Eirene` class isn't that tightly coupled to the file format to justify different classes for different file formats, I think.

**Review by Mateasek — APPROVED** [review]
I tested it on our SOLPS output with  20170328  3.0.6-81-ga3fccb2              
 fort.44 version and it works flawlessly, thanks for adding the parsing function for the new version @jacklovell

**Pull request merged**
