### PR TITLE
Use generomak first wall for imaging plasma demo script

### PR DESCRIPTION
**Pull request by jacklovell**
Now that the mesh for the first wall is in core/development, use it to make the
demo where the SOLPS simulation is imaged with a camera into a more
compelling demonstration.

### CODE REVIEW

**Comment by vsnever** [comment]
I rendered this at higher resolution and with better statistics. Looks nice!
generomak_raw_files_image_plasma

**Comment by jacklovell** [comment]
Yes, it really does produce a nice image with higher resolution and more rays. Unfortunately I think the run time to produce an image of this quality wouldn't be suitable for a demo, but perhaps we can use this illustration in the HTML documentation once that starts to include generomak components.

**Comment by vsnever** [comment]
To render this image, I pre-calculated the total radiation on the SOLPS grid and then used the `RadiationFunction` emitter. The rendering took ~20 min, but we should leave this for a separate demo.

**Review by Mateasek — APPROVED** [review]
Fine by me. This will provide awesome pictures

**Comment by Mateasek** [comment]
Just to the high-resolution case, users can simply increase the number of pixels and use the same demo to get a better resolution image. I don't think there is a need for 2 separate demos. The image @vsnever generated can be used for illustrations as @jacklovell said.

**Pull request merged**
